### ISSUE TITLE
Controller - Anschaungsmodus: Boolean an Exercise page mitliefern

### ISSUE THREAD

**Issue by alexanderj1988** [hydranox/foo-pub#101]
Es wäre sehr schön, wenn man in der Exercise noch einen Boolean mitbekommt, ob man in einem Anschaungsmodus oder Aufgabenmodus ist.

Dadurch wäre es bei Streitpunkten möglich Aufgabenstellung und Lösung + Eingabe gegenüberzustellen.

**Comment by hydranox** [comment]
#118
und das neue Requirement, dass man beim Scrollen nicht verhungern soll.
