### ISSUE TITLE
Zugriffsrecht für Solutionpage für Tutoren sichern, aber nicht für Studis

### ISSUE THREAD

**Issue by alexanderj1988** [hydranox/foo-pub#104]

**Comment by hydranox** [comment]
Critical Tag entzogen, da nicht so kritisch ;)
Milestone ebenfalls aktualisiert.

**Comment by hydranox** [comment]
Erstmal nur für Administratoren, sowohl Normal als auch Testatsbetrieb. Ist drin!

**Comment by hydranox** [comment]
Bug in #168 aufgetreten, re open

**Comment by hydranox** [comment]
Okay, schnell gefunden. 
" where user=0 (ich) ".... -.-

**Comment by hydranox** [comment]
Requirement für #6
