### ISSUE TITLE
Lösungsseite Undefined index: passed

### ISSUE THREAD

**Issue by drcicero** [hydranox/foo-pub#109]
Folgende Fehlermeldung wurde nach Beantworten einer Frage unter der Lösung angezeigt:
(mit - glaub ich - einem falsch ausgefülltem Kästchen, falls das relevant ist;
beim Thema Stringmatching Endlicher Automat, da sich das scheinbar nicht aus dem Stacktrace ergibt...)

    Internal Server Error

    Undefined index: passed

    • /var/www/foo/tmp/5sgx9eful27o.1lsdc1z20tgbf.php:169 Base->{closure}()
    • /var/www/foo/lib/base.php:2075 require()
    • /var/www/foo/lib/base.php:2211 View->sandbox()
    • /var/www/foo/tmp/5sgx9eful27o.w87adxk12ect.php:120 Preview->render()
    • /var/www/foo/lib/base.php:2075 require()
    • /var/www/foo/lib/base.php:2211 View->sandbox()
    • /var/www/foo/inc/controllers/ExerciseController.php:104 Preview->render()
    • /var/www/foo/lib/base.php:1305 Base->call()
    • index.php:54 Base->run()

Ich hoffe das hilft! :smiley:

**Comment by hydranox** [comment]
Vielen Dank!
Da ist noch ein Überbleibsel einer Konventionsänderung. Dürfte in innerhalb der nächsten Stunden gefixt sein.

**Comment by alexanderj1988** [comment]
gefixt
