### ISSUE TITLE
Teilweise korrekte Lösung als Vorschlag bei Klick ins Feld (String-Matching)

### ISSUE THREAD

**Issue by jojowi** [hydranox/foo-pub#112]
Ich hatte grade bei der Simple String Matching-Aufgabe einige korrekte Lösungen "bekommen":
Beim Klick in einige der Eingabefelder bei "R" kam als Vorschlag jeweils die korrekte Lösung. Dies war jetzt das erste Mal, das ich sowas gesehen habe und auch nur bei einigen Feldern, also könnte es Zufall sein (bei einer vorherigen Aufgabe könnte ich vielleicht diese Eingaben gemacht haben???).
Allerdings halte ich die Chance für einen Zufall bei Zeichenketten wie "(115,2);(110,7)" oder ähnlich schon sehr gering. Ich wollte es euch einfach nur mitteilen, vielleicht kann man die Vorschläge auch komplett unterbinden?

Johannes

**Comment by alexanderj1988** [comment]
ja das ist Zufall. Das keine vorschläge mehr in dem Eingabefeldern erscheint ist allerdings eine gute idee. Dies sollte bis zum nächsten patch vorhanden sein
mfg Alex 


     Johannes Wirth <notifications@github.com> schrieb am 13:18 Donnerstag, 16.April 2015:
   

 Ich hatte grade bei der Simple String Matching-Aufgabe einige korrekte Lösungen "bekommen":
Beim Klick in einige der Eingabefelder bei "R" kam als Vorschlag jeweils die korrekte Lösung. Dies war jetzt das erste Mal, das ich sowas gesehen habe und auch nur bei einigen Feldern, also könnte es Zufall sein (bei einer vorherigen Aufgabe könnte ich vielleicht diese Eingaben gemacht haben???).
Allerdings halte ich die Chance für einen Zufall bei Zeichenketten wie "(115,2);(110,7)" oder ähnlich schon sehr gering. Ich wollte es euch einfach nur mitteilen, vielleicht kann man die Vorschläge auch komplett unterbinden?Johannes—

**Comment by hydranox** [comment]
<input type="text" autocomplete="off">
Bitte testen
