### ISSUE TITLE
Minimalzeitpunkt i!=0 bei MergeSort?

### ISSUE THREAD

**Issue by jojowi** [hydranox/foo-pub#113]
Beim Mergesort muss der Zustand zu einem Zeitpunkt i angegeben werden.
Ich hatte jetzt einige Aufgaben mit i=0 was dann relativ sinnlos ist, da man einfach bei beiden Zeigern 0 eingibt und fertig ist.
Vielleicht sollte man einen minimalen Zeitpunkt i einbauen?

Johannes

**Comment by alexanderj1988** [comment]
danke, sollte mit dem nächsten update behoben sein 


     Johannes Wirth <notifications@github.com> schrieb am 13:25 Donnerstag, 16.April 2015:
   

 Beim Mergesort muss der Zustand zu einem Zeitpunkt i angegeben werden.
Ich hatte jetzt einige Aufgaben mit i=0 was dann relativ sinnlos ist, da man einfach bei beiden Zeigern 0 eingibt und fertig ist.
Vielleicht sollte man einen minimalen Zeitpunkt i einbauen?Johannes—
