### ISSUE TITLE
Mergesort: Welche Liste bei Gleichheit gewählt wird

### ISSUE THREAD

**Issue by jojowi** [hydranox/foo-pub#114]
Vielleicht könnte man bei der Beschreibung des Mergesort-Algorithmus angeben, aus welcher Liste die Zahl gewählt wird, wenn beide Zeiger auf die selbe Zahl zeigen. (sie wird aus der zweiten Liste genommen)

Johannes

**Comment by alexanderj1988** [comment]
danke ist hinzugefügtt und sollte beim nächsten patch geupdated sein 


     Johannes Wirth <notifications@github.com> schrieb am 13:28 Donnerstag, 16.April 2015:
   

 Vielleicht könnte man bei der Beschreibung des Mergesort-Algorithmus angeben, aus welcher Liste die Zahl gewählt wird, wenn beide Zeiger auf die selbe Zahl zeigen. (sie wird aus der zweiten Liste genommen)Johannes—
