### ISSUE TITLE
Usability: String Matching

### ISSUE THREAD

**Issue by jojowi** [hydranox/foo-pub#115]
Bei beiden String-Matching-Übungen ist es sehr problematisch die korrekte Position im Suchstring zu finden, vor allem bei sehr hohen Startwerten von z.B. 100.
Entweder eine regelmäßige Markierung (alle 10 Zeichen oder so) oder direkt eine Markierung der Stelle an der man anfangen muss wäre praktisch

**Comment by alexanderj1988** [comment]
fiexed
