### ISSUE TITLE
HashTable: Internal Server Error und kein (funktionierender) "Abgeben"-Button

### ISSUE THREAD

**Issue by katrinBe** [hydranox/foo-pub#116]
Hallo!
Bei den Aufgaben zu den HashTabels sind bei mir diverse Fehler aufgetreten:
Beim Starten einer Aufgabe zu "Quadratic Probing" erscheint eine Aufgabe mit zwei Werten für K, danach folgt ein "Internal Server Error: file_get_contents(/var/www/foo/public/tmp/PTXeUe4Lv.log): failed to open stream: No such file or directory". Außerdem funktionieren bei dieser Ansicht fast alle Buttons ("Aufgaben", Profil, aktuelle Aufgaben) nicht mehr. Es exisitert auch kein "abgeben"-Button, folglich komme ich aus der Aufgabe nicht mehr raus. Nur der "Übersicht"-Button funktioniert noch. Als ich dann nachsehen wollte, ob dieser Fehler mehrfach auftritt, habe ich ausversehen auf "Linear Probing" gedrückt und auch hier Fehler festgestellt. Ich konnte also parallel noch eine zweite Aufgabe starten (soll das gehen?), diese allerdings auch nicht mehr Verlassen, da beim "Linear Probing" der "Abgeben"-Button zwar vorhanden ist, aber nicht funktioniert. Ich hab also jetzt zwei Aufgaben gestartet, aus denen ich nicht mehr rauskomme.
Hier auch nochmal die Adressen:
Linear Probing: https://foo.algo.informatik.tu-darmstadt.de/exercise/0/74bba22728b6185eec06286af6bec36d

Quadratic Probing: https://foo.algo.informatik.tu-darmstadt.de/exercise/1/b7892fb3c2f009c65f686f6355c895b5

PS: mir ist aufgefallen, dass bei den anderen Aufgaben das Drücken von Enter gleichbedeutend mit dem Abgeben-Button ist, wäre vielleicht ganz gut hier noch eine Abfrage nach dem Motto "Wirklich abgeben?" einzufügen, da hier eventuell mit Enter unbeabsichtigt abgegeben wird, bevor man alle Daten eingetragen hat...

**Comment by hydranox** [comment]
Der erste Part ist gefixt.
Zweite Part kommt in ein neues Ticket.
