### ISSUE TITLE
Abgabe: Bist du sicher Dialog?

### ISSUE THREAD

**Issue by hydranox** [hydranox/foo-pub#117]
bei den anderen ist Aufgaben das Drücken von Enter gleichbedeutend mit dem Abgeben-Button ist, wäre vielleicht ganz gut hier noch eine Abfrage nach dem Motto "Wirklich abgeben?" einzufügen, da hier eventuell mit Enter unbeabsichtigt abgegeben wird, bevor man alle Daten eingetragen hat...

**Comment by FabianSchuessler** [comment]
ist mir auch schon passiert

**Comment by hydranox** [comment]
Done.
