### ISSUE TITLE
Solitionpage: Mehr Informationen über Aufgabenstellung

### ISSUE THREAD

**Issue by hydranox** [hydranox/foo-pub#118]
Alle wichtigen Informationen aus der Aufgabenstellung müssen auf der Solutionpage ersichtlich sein.
Referenz: Hashtable exercises

**Comment by hydranox** [comment]
Assignment zu Alex, da z.B. beim Stringmatcher der String fehlt :/

**Comment by alexanderj1988** [comment]
fertig
