### ISSUE TITLE
Generelle Verbesserungsvorschläge

### ISSUE THREAD

**Issue by FabianSchuessler** [hydranox/foo-pub#119]
In der Mergesort Lösung steht "Ergebnissliste: l2:" obwohl eigentlich "Zeiger l2:" dort stehen sollte.

Und bei String matching based on finite automaton bitte auch das Leerzeichen nach fünf Ziffern bei Match String einbauen.

Danke.

Außerdem würde ich bei jeder Lösung noch mal die Aufgabenstellung zur Verfügung stellen, das wäre wirklich sehr hilfreich.

Außerdem stimme ich zu, dass das Multiplizieren von fünf und das Abzählen bis zum richtigen Block wohl nicht Sinn der String Matching Aufgaben sein sollte.

**Comment by hydranox** [comment]
"Außerdem würde ich bei jeder Lösung noch mal die Aufgabenstellung zur Verfügung stellen, das wäre wirklich sehr hilfreich."
#118

**Comment by alexanderj1988** [comment]
fixed.
Das mit der Aufgabenstellung steht in einem seperatem Ticket
