### ISSUE TITLE
Hashtable Linear Probing: In den einzelnen Schritten wird beim Latexinhalt nicht das aktuelle Element angezeigt

### ISSUE THREAD

**Issue by FabianSchuessler** [hydranox/foo-pub#121]
z.B. : k mod 12
dann bei den Einzelschritten wird das konkrete k immer weggelassen wie: mod 12 = 1

Das Laden dauert ewig, das liegt wahrscheinlich an der Generierung der Latex Bilder und kann nicht optimiert werden?

**Comment by hydranox** [comment]
![kmod](https://cloud.githubusercontent.com/assets/9027061/7337256/455f5352-ec24-11e4-877a-33cec58672bd.PNG)

"Das Laden dauert ewig, das liegt wahrscheinlich an der Generierung der Latex Bilder und kann nicht optimiert werden?"
Sehr gut beobachtet. Eine LaTeX Generierung ist verdammt teuer für "dynamische" Formeln. Vor allem, wenn es davon ca. 30-40 Stück auf einer Seite gibt, da ich in der Meinung bin, dass man an "Erklärungen" nicht sparen sollte, auch nicht an CPU Auslastung. Es ist ein Caching Verfahren implementiert, d.h. eine "K4 = 5" Formel, welche schon mal generiert wurde, wird wieder verwendet und nicht neu generiert.

**Comment by hydranox** [comment]
![nmax](https://cloud.githubusercontent.com/assets/9027061/7337297/8fd62e78-ec25-11e4-94c6-96c7eaea2100.PNG)
haben ebenfalls eine whitespace bei Quadratic Probing nachgefixt.
![nmax2](https://cloud.githubusercontent.com/assets/9027061/7337306/e2eac33a-ec25-11e4-89ff-2a8e3e79c34f.PNG)
![nmax3](https://cloud.githubusercontent.com/assets/9027061/7337308/e7477bbc-ec25-11e4-863d-3d4e30762a7c.PNG)
