### ISSUE TITLE
Schriftart ändern

### ISSUE THREAD

**Issue by JojoSc** [hydranox/foo-pub#122]
Ich schlage vor, bei den Stringmatchern die Strings in einer Monospace-Schriftart (z.B. Courier New) darzustellen. Besonders bei Strings wie "fflil" u.ä.verzählt man sich schnell mal, da die Buchstaben so nahe bei einander sind.

**Comment by hydranox** [comment]
Gute Idee, der Zuständige hat wahrscheinlich auch nicht bedacht, wie nervig ein string wie "ijlijlijiilljil" sein könnte.
![idee](https://cloud.githubusercontent.com/assets/9027061/7337428/cd957eea-ec29-11e4-92ac-05fd7742a0a9.PNG)
Lösung:
style="font-family:'Courier New', Arial;"
Ist an den entsprechenden Bearbeiter deligiert.

**Comment by alexanderj1988** [comment]
erledigt
