### ISSUE TITLE
Reiter zur Gruppeneinwahl fehlt

### ISSUE THREAD

**Issue by TristanGah** [hydranox/foo-pub#128]
Hallo,
wie der Titel schon vermuten lässt fehlt bei mir der Reiter zum eintragen in die Gruppe, auch der Link aus der Mail bringt mich nicht auf die Seite, bekomme lediglich eine Fehlermeldung, dass der Server nicht erreicht werden konnte. Bekomme ich den Link von einem Kommilitonen funktionierts und ich kann mich auch einloggen aber die Möglichkeit zur Terminwahl fehlt.
Kann mir wer helfen?

**Comment by hydranox** [comment]
Das Problem lag vor, da viele der Studies sich bis dato noch nie in foo angemeldet hatten und wir sie deshalb nicht in den priviligierten Rang heben konnten, der für die Testatseinwahl vorgesehen war.
Das Problem hat sich durch die neue Whitelisting Funktion reguliert.
