### ISSUE TITLE
Frage zu Mergesort - Werden beim letzten Element die Zeiger wirklich nicht weitergezählt?

### ISSUE THREAD

**Issue by FabianSchuessler** [hydranox/foo-pub#129]
Titel sagt schon alles, ein Bild noch als Beispiel.

Iteration 22.

![untitled](https://cloud.githubusercontent.com/assets/10107422/7411321/4829511c-ef37-11e4-9849-d60a605fdc90.png)

**Comment by alexanderj1988** [comment]
wenn der merge am ende von der einen liste angekommen ist, wird auch der pointer nicht mehr weitergezählt, da an der stelle der REST der anderen liste angehängt wird.
mfg alex 


     FabianSchuessler <notifications@github.com> schrieb am 12:49 Donnerstag, 30.April 2015:
   

 Titel sagt schon alles, ein Bild noch als Beispiel.Iteration 21 und 22.—

**Comment by hydranox** [comment]
BTW: Das ist nicht Mergesort, sondern Merge, ein Teilalgo des Mergesorts. Bloß nicht verwechseln!
