### ISSUE TITLE
Regex beim StringMatching akzeptiert nicht alle Eingaben

### ISSUE THREAD

**Issue by RedundantRedundant** [hydranox/foo-pub#131]
Das Regex beim String-Matching akzeptiert nicht alle gültigen Eingaben:

`[0-9]+(,[0-9]+)?`

sollte eigentlich

`[0-9]+(,[0-9]+)*`

sein. 

Nicht akzeptiert wurde das in Foo angebene Beispiel "40,83,110"

Außerdem wurde trotz richtiger Lösung "Ihre Lösung ist nicht korrekt" angezeigt.
Screenshot im Anhang

![clip](https://cloud.githubusercontent.com/assets/12189489/7419158/899ddcee-ef73-11e4-9628-9892fde95685.jpg)

**Comment by hydranox** [comment]
Das mit dem Regex: Gut erkannt, Habe soeben einen Hotfix eingespielt.. Sorry :/

Das Mit der falschen Richtigen Lösung: Der Hotfix wird leider erst morgen gemacht. Ich werde Sie dir gleich als korrekt anerkennen. Danke!

**Comment by alexanderj1988** [comment]
könnte man den seed der aufgabe haben? dann können wir den fall genau nachvollziehen

mfg alex

**Comment by SuperN1ck** [comment]
Die Regex sind bei mir leider immer noch falsch.

**Comment by RedundantRedundant** [comment]
Seed der Aufgabe: `d47268e9db2e9aa3827bba3afb7ff94a`

**Comment by alexanderj1988** [comment]
clear (schon ewig, aber vergessen zu closen :/)
