### ISSUE TITLE
Im Dashboard sollten die Aufgaben des Testats gut erkennbar sein.

### ISSUE THREAD

**Issue by rezoddozer** [hydranox/foo-pub#133]
Entweder bei der Liste der Testate sollten in Label die Aufgaben stehen.
Oder das Dashboard bekommt ein Label in dem genau zum nächsten Testat Details angezeigt werden:
1. Termin
2. Aufgaben die dran kommen
3. Statistik über die Aufgaben die dran kommen

Oder lasst euch was anderes einfallen.
Im D120 forum wurde schon nach den Aufgaben gefragt, die drankommen und zur Zeit kann man das nur unintuitiverweise bei der Terminwahl nachschlagen.

**Comment by hydranox** [comment]
1. Ist da. Besser in Zukunft nachschauen.
2. Wenn man draufklickt, kommt man dahin. Dashboard sollte nicht überladen sein an dieser stelle.
3. Woanders vorgesehen.

4. Die Informationen waren aus den Ankündigungen zu entnehmen. Testat 1 ist lange genug im foo angekündigt. Testat 2 siehe #134
