### ISSUE TITLE
Algowiki: Fehler bei "Pivot partitioning by scanning"

### ISSUE THREAD

**Issue by FHees** [hydranox/foo-pub#141]
Die Variable n wird inkonsistent benutzt:
Im Punkt 1.3 der Invariante ist (leicht nachrechenbar) n gleich der Anzahl der Elemente plus 1
Im weiteren Artikel wird n aber scheinbar für die Anzahl der Elemente benutzt.

Ursache könnte ein Fehler in Punkt 1.1 sein:
Wenn es dort "m_1 elements less than p" hieße, wäre n überall gleich der Anzahl der Elemente.

**Comment by hydranox** [comment]
hydranox/algowiki-pub/issues/7
