### ISSUE TITLE
Aufgabe: Pivot Partitioning - Aufgabenstellung verbessern

### ISSUE THREAD

**Issue by FHees** [hydranox/foo-pub#142]
Weder aus dem Wikiartikel, noch aus der Aufgabenstellung geht hervor, welche Aktionen in einem Induktionsschritt passieren.

Eine Erwähnung verdienen meiner Meinung nach mindestens flogende Punkte:
* Die **Initialisierung von i_1 bis i_3 zählt als Schritte** (jede Erhöung ein Schritt) [Wiki: Induction basis - Implementation - Schritte 8 - 10]
* **Beim Tauschen der Elemente wird i_2 oder i_3 hochgezählt** (zählt zusammen als ein Schritt)
(ggf noch überprüfen ob i_2 und i_3 beide hochgezählt werden wenn S[i_2] mit S[i_3] getauscht wird - Ist wahrscheinlich, konnte ich aber noch nicht testen)

Und für die Noobs noch:
* **Gezählt wird ab Index 0**

**Comment by karweihe** [comment]
Am 7. Mai 2015 um 13:38 schrieb FHees <notifications@github.com>:

> Weder aus dem Wikiartikel, noch aus der Aufgabenstellung geht hervor,
> welche Aktionen in einem Induktionsschritt passieren.
>

Auf der Wiki-Seite "Pivot partitioning by scanning" finden Sie nichts dazu!?

Die Seite "Pivot partitioning" beschreibt die Problemstellung.

Freundliche Grüße,

Karsten Weihe

-- 

Prof. Karsten Weihe
Hochschulstr. 10, 64289 Darmstadt, Germany
Phone: +49-6151-16-20870
Fax: +49-6151-16-20873
www.algo.informatik.tu-darmstadt.de

**Comment by hydranox** [comment]
@FHees bitte wie Besprochen noch mal ausformulieren. Danke!

**Comment by FHees** [comment]
Grundproblem:
Wie bereits geschrieben, liegt das Problem darin, dass nicht ganz klar ist welche Änderungen eigentlich in einer Iteration passieren.
Das geht weder aus der Aufgabenstellung, noch aus dem [Wikiartikel] (http://wiki.algo.informatik.tu-darmstadt.de/index.php/Pivot_partitioning_by_scanning) (Ich meine den mit dem Algorithmus, der in der Aufgabe verwendet wird, nicht den, mit der Problemdefinition!) hervor.
Im Konkreten geht es um folgendes:

1. Initialisierung.
In der Aufgabe wird die Initialisierung der i Pointergewertet als Iterationsschritte.
Das ist sowohl zur Implementation im Wiki als auch zu anderen Aufgaben inkonsistent.
Zur Wiki insofern, als dass die Initialisierung dort mit dem Hochzählen der Pointer endet (Schritte 8.-10. der Initialisierung),
in der Aufgabe dagegen ist die Initialisierung mit i1 = 0; i2 = m1; i3 = m2 vorbei und die ersten Iterationsschritte sind die weitere Initialisierung dieser Werte.
Zu anderen Aufgaben wie z.B. Dijkstra oder auch beim Stringmatching Automat, bei denen die Initialisierung und Preprocessing nicht als Iterationsschritte zählen.

2. Inkrementierung von i2 und i3
Im Wikiartikel ist das Inkrementieren von i2 bzw. i3 nach dem Tauschen zweier Werte in einem Punkt erwähnt. (i = i + 1 until ...).
Ich dachte erst das heißt entweder, dass das Hochzählen von i komplett als ein Iterationsschritt gewertet wird (oder gar nicht, weil es zum Tauschen gezählt wird),
oder dass jedes Inkrementieren des Werts als ein Iterationsschritt gezählt wird.
Tatsächlich arbeitet die Aufgabe aber folgendermaßen:
Das erste Inkrementieren von i nach dem Tauschen wird nicht als Iterationsschritt gezählt (gehört zum Tauschen der Werte).
Jedes weitere Inkrementieren von i zählt als Iterationsschritt.

Fazit
Insgesamt arbeitet die Aufgabe zwar in der Theorie sinnvoll (in jeder Iteration wird ein i Pointer inkrementiert) - allerdings zu Kosten der Benutzbarkeit und Konsistenz zur Wiki und anderen Aufgaben.

Kurze persönliche Anmerkung:
Ich habe nach Durcharbeiten des Wikiartikels und durchgehen auf Papier trotzdem noch 6 Versuche gebraucht, um herauszufinden, wie genau die Aufgabe funktioniert.

**Comment by karweihe** [comment]
Ich habe im Pseudocode im Wiki ein paar Fehler korrigiert, die wohl bei der
großen Umziehaktion Anfang 2015 hineingekommen sind (jedenfalls während der
letzten GdI II noch nicht drin waren).

-- 

Prof. Karsten Weihe
Hochschulstr. 10, 64289 Darmstadt, Germany
Phone: +49-6151-16-20870
Fax: +49-6151-16-20873
www.algo.informatik.tu-darmstadt.de

**Comment by hydranox** [comment]
Dürfte seit meinem Refactoring vom Samstag passen...
