### ISSUE TITLE
Lösungen der Aufgaben mit Enter abschicken

### ISSUE THREAD

**Issue by Loriot2015** [hydranox/foo-pub#146]
Hallo zusammen,

mir ist es beim Bearbeiten der Aufgaben nun schon zeimal passiert, dass ich mit Betätigen der Enter-Taste die Lösung ungewollt vorzeitig abgeschickt habe. Eventuell wäre zu überlegen, dass man die Aufgaben nur mit einem Klick auf die Schaltfläche "Drücken zum Fortfahren" beenden kann.

Viele Grüße,
Loriot 2015

**Comment by jojowi** [comment]
Meines Wissens ist das geplant, aber wohl noch nicht (überall) umgesetzt

**Comment by hydranox** [comment]
#117
