### ISSUE TITLE
Anmeldung zum testat wurde nicht akzepiert.

### ISSUE THREAD

**Issue by AimBlacc** [hydranox/foo-pub#148]
Ich habe mich zum ersten Testat angemeldet und habe den Termin schon eingetragen aber der Termin erscheint nicht mehr, nach dem ich heute nochmal alles überprüfen wollte.

**Comment by AimBlacc** [comment]
Hat sich geklärt war ein Fehler meiner Seite. Aber jetzt kann ich mich nicht mehr anmelden, kann bitte eine Ausnahme gemacht werden, damit ich doch noch an den Testat Teilnehmen kann ?

**Comment by hydranox** [comment]
Da es sich hierbei um kein "Ticket" bezüglich der Funktionalität handelt, sondern um ein persönliches Anliegen - zudem einen Individualfall, bitte ich Sie eine Mail an mich zu schreiben, da das nicht hier her gehört und ich hier Ihre Identität nicht entschlüsseln kann ;)
