### ISSUE TITLE
Accounterstellung bei GitHub notwendig, um Ticket einzureichen

### ISSUE THREAD

**Issue by 0815-4711** [hydranox/foo-pub#150]
Leider muss man einen Account bei GitHub besitzen oder einrichten, wenn man ein Ticket einreichen will. Könnte einmal datenschutzrechtlich Problematisch sein (durch verküpfung Student im GdI2 Kurs und Aktivitäten bei GitHub) und ist auch für alle schlecht, die sich keinen Account einrichten wollen. Sollte aus dem foo-System heraus möglich sein, wenn diese Option schon angeboten wird.
Außerdem sollte man kennzeichnen, dass man sich bei klicken auf "Ticket einreichen" nicht mehr im foo-System befindet sondern weitergeleitet wird (auch so´n Daten- bzw. Verbraucherschutzding, weiß nicht genau, wo man das ansiedeln muss).

**Comment by hydranox** [comment]
Niemand hat je behauptet, dass Github verpflichtend ist.
Den Vorwurf, dass wir irgendwie versuchen sollten, irgendwelche Timestamps mit Github abzugleichen, werde ich an dieser Stelle gepflegt ignorieren und dieses Ticket schlichtweg schließen.

Eine komfortable Lösung wie Github in foo selbst zu implementieren, wäre nicht vertretbar, vor allem nicht in Anbetracht dessen, von welchem Aufwand und welchen Geldern wir hier reden.

foo weist mehrere externe Links auf und rein rechtlich sind wir diesbezüglich Abgesichert.
Ich gebe zu, eine Warnung wäre "Nice to have", aber auch nervig. Vielleicht in Zukunft.

**Comment by 0815-4711** [comment]
Schade, dass du das als Vorwurf interpretierst. Ich bin nicht der meinung, dass ihr Timestamps abgleicht, sondern dass die allein die Tatsache, dass z.B. diese Möglichkeit besteht, eventuell zu Problemen führen kann. Ich habe mich aufgrund von eigenen Web-Projekten mit dieser Thematik schon intensiver auseinandergesetzt und wollte lediglich auf Probleme, welche auch durch nicht ganz klare Richtlinien seitens des Gesetzgebers entstehen können, aufmerksam machen.
Ich denke, dass foo ein gutes Projet ist und dass es schade wäre, wenn dieses Projekt durch solche Probleme schaden nehmen könnte.

btw.
Welche Links sind denn noch extern? Also ausserhalb des TU- Netztes? Ich habe jetzt keine gefunden.
Als eventuelle Lösung für dieses Problem hab ich an etwas wie einen foo- Account bei GitHub gedacht, also einen Account für alle user von foo, so dass ein Ticket dann aus dem System heraus auf GitHub gesetzt werden kann. Auch wenn ihr dass jetzt nicht schafft, man kann sowas ja in den Katalog für die Weiterentwicklung  aufnehmen (falls es mal ein neues Budget geben sollte).
