### ISSUE TITLE
Terminüberschneidung mit foo-Testat

### ISSUE THREAD

**Issue by Janosch1711** [hydranox/foo-pub#151]
Hallo,

habe leider erst heute festgestellt das sich mein Termin für das Praxistestat minutengenau mit dem des foo-Testates überschneidet.

Ich habe die Termine mit meinem Theorietestaten verwechselt und hatte mich blind darauf verlassen bis der Fehler mir, nach vergeblicher Warterei im C-Pool auf den Tutor, auffiel.

Ich weiß mir überhaupt nicht mehr zu helfen.
Weiß irgendjemand ob es eine, auch so geringe, Chance gibt den Termin zu verschieben?
Oder kann mir jemand sagen an wen ich mich bei so Themen richten kann?

Es wäre sehr ärgerlich wenn ich nur durch diese pure Blödheit meinen ersten Fehlversuch kassiere.

**Comment by hydranox** [comment]
Da es sich hierbei um kein "Ticket" bezüglich der Funktionalität handelt, sondern um ein persönliches Anliegen - zudem einen Individualfall, bitte ich Sie eine Mail an mich zu schreiben, da das nicht hier her gehört und ich hier Ihre Identität nicht entschlüsseln kann ;)
