### ISSUE TITLE
String matching FA - Result List not initalized correctly?

### ISSUE THREAD

**Issue by joshimoo** [hydranox/foo-pub#152]
if you look at the below exercise you will see, that the result list does not get initialized with the prior result indexes. https://foo.algo.informatik.tu-darmstadt.de/solution/6/d7cbbc7d02fca8a32ac5a3b5161ee19c

All prior exercises I completed, did have the previous result indexes correctly initialized.
Therefore I don't think that this is expected behavior. Please let me know if you require additional information.

**Comment by joshimoo** [comment]
Another Example, where the Result List was not initialized correctly.
https://foo.algo.informatik.tu-darmstadt.de/solution/6/7f8a689b0c8adf6213e67688ce750090

@karweihe Since my Testat is tomorrow, I would like to know if this is expected behavior, even tough in all but 2 of my tries, the result list was always initialized properly before.

If this is not a bug, a person would need to go through all previous 150 iterations just to make sure that the result list is initialized correctly.

**Comment by alexanderj1988** [comment]
i don't realy see the error

**Comment by joshimoo** [comment]
Thank you for investigating, then I must have overlooked them. 
Even tough I had the feeling that I did not.
Is there a way to restart a specific seed?

**Comment by hydranox** [comment]
@joshimoo Not yet, #6
