### ISSUE TITLE
Anpassng Zeitleiste Testatsmodus

### ISSUE THREAD

**Issue by alexanderj1988** [hydranox/foo-pub#155]
Die Zeitleiste ist für manche leute irritierend und runterscrollen ist keine schöne usability methode.

Der Vorschlag ist daher die Zeitleiste auszublenden. Des weiteren wäre es gut wenn die Zeitleiste noch ein bisschen Dezenter ist.

**Comment by hydranox** [comment]
Man kann nun im Testatsmodus am linken Rand auf eine Uhr klicken, um die Countdownleiste aus- bzw. einzublenden.
