### ISSUE TITLE
Pivot Partitioning Ergebnisliste zu lang

### ISSUE THREAD

**Issue by robtothein** [hydranox/foo-pub#157]
![unbenannt](https://cloud.githubusercontent.com/assets/12574575/7784728/89148fca-0170-11e5-8208-822872bdb0e3.png)
![unbenannt2](https://cloud.githubusercontent.com/assets/12574575/7784729/8dae2bc2-0170-11e5-9865-6129a9edade1.png)

(Wenn ich auf 90% Zoom einstelle, passt es.) 

PS: Ergebnisliste wurde mit zwei "s" geschrieben

**Comment by hydranox** [comment]
Passt es jetzt? Bitte überprüfen und das Ticket schließen.
