### ISSUE TITLE
Kurzzeitmeldung kann nicht als gelesen markiert werden.

### ISSUE THREAD

**Issue by JustusKempfer** [hydranox/foo-pub#158]
Hi,

ich hab den Bug, dass die unterste der Kurzzeitmeldungen direkt nach dem Text endet und man nicht weiter runterscrollen kann.
Das heißt, das (eventuell existierende) Häkchen "als gelesen markieren" kann nicht angeklickt werden.
Somit habe ich durchgehend die Anzeige, dass ich noch eine ungelesene Meldung habe.

Eine "alle Meldungen als gelesen markieren" - Option würde dieses Problem übrigens umgehbar machen und wäre auch allgemein sehr praktisch, wenn die Meldungen in Zukunft weiterhin in dieser Frequenz eintreffen.

Freundliche Grüße,
Justus Kempfer

**Comment by hydranox** [comment]
Hallo Justus,
ich eben das Reworking an diesem Modul begonnen.
Das Problem dürfte in wenigen Stunden nicht mehr existieren.
TL

**Comment by hydranox** [comment]
Ich werde in innerhalb der nächsten Stunde eine weitere Nachricht bezüglich einer Änderung veröffentlichen. Wenn dir die meine Lösung für das Problem nun gefällt, dann schließ bitte das Ticket oder gib mir noch ein paar Anmerkungen.
Danke!
