### ISSUE TITLE
MergeSort Hinweis über Doppelte Einträge

### ISSUE THREAD

**Issue by BlackWiddow** [hydranox/foo-pub#159]
Hallo!
foo ist super gemacht!
Nur eine kleine Frage habe ich, nämlich steht als Hinweis, dass falls doppelten Einträgen die Zahl aus der zweiten Liste genommen werden soll. Dies habe ich getan, doch dann war meine Lösung  falsch.
In Ihr wurde (wie im Bild zu sehen) immer auch das doppelte Element mit rein genommen. Habe ich den Hinweis etwa falsch verstanden? Falls ja, bitte ich um Entschuldigung!

MfG
A.A.
![aufgabenstellung](https://cloud.githubusercontent.com/assets/9130071/7799540/a53b02ea-0307-11e5-9735-86ce9234f29c.png)
![solution](https://cloud.githubusercontent.com/assets/9130071/7799541/a53fbe5c-0307-11e5-8502-4fd6d71382a5.png)

**Comment by hydranox** [comment]
Wieso kommt bei deiner Eingabe keine zweite -1 vor der 0 ?
Ich gehe mal die Aufgabe frei im Kopf durch:
-15U,-14U,-13O,-12U,-11O,-9U,-6O,-2O,-1U,-1O,0O,....

Beim "Aha" Effekt das Ticket bitte schließen, danke ;)

**Comment by BlackWiddow** [comment]
Aaaaahh alles klar danke! :)
