### ISSUE TITLE
Lösungen können nicht angezeigt werden.

### ISSUE THREAD

**Issue by JustusKempfer** [hydranox/foo-pub#168]
Hi,

seit kurzer Zeit wird mir nach der Abgabe diese Fehlermeldung gezeigt:
![fooerror1](https://cloud.githubusercontent.com/assets/12599454/7803573/e2458d8a-0353-11e5-9ca9-ca142de7ec58.PNG)
Danach kann ich auf der Auswahlseite allerdings noch erkennen, ob ich alles richtig hatte oder nicht.
Das Ergebnis wird also korrekt gespeichert, nur der schöne Bildschirm mit der korrekten Lösung wird nicht angezeigt.
Trotzdem ist dies vor allem in den Fällen, in denen man nicht richtig liegt, störend.

Das Ganze geschieht bei mir bei BucketSort und Merge, den Rest habe ich noch nicht versucht.

Freundliche Grüße,
Justus Kempfer

**Comment by hydranox** [comment]
Überprüfs nochmal, dürfte jetzt wieder passen.

**Comment by hydranox** [comment]
Die #104 hat das Problem ausgelöst. Muss ich wohl nochmal ran. Bitte schließen wenn es geht, danke :)
