### ISSUE TITLE
Merge-Test buggt, wenn nach allerletzter Iteration gefragt wird.

### ISSUE THREAD

**Issue by JustusKempfer** [hydranox/foo-pub#172]
Hi,

ich hatte eben den seltenen Fall, dass im Merge-Test der Zustand nach der letzten (in diesem Fall der 23.) Iteration anzugeben war.
Die Lösung hier ist natürlich relativ klar. Nämlich die vollständig zusammengeführte Liste sowie die Zeigerpositionen der beiden Listen auf dem jeweils letzten Listelement, also |l1| und  |l2|, die bekannte Abbruchbedingung.
Foo war aber anderer Meinung:
![image](https://cloud.githubusercontent.com/assets/12599454/7820769/9a0fadec-03ea-11e5-8a04-8f498588a0ee.png)
(..)
![image](https://cloud.githubusercontent.com/assets/12599454/7820707/30a2851e-03ea-11e5-853e-56b89ecc9c7e.png)
Der Fehler scheint also nur in der allerletzten Iteration zu liegen.
Diesen Bug weiter zu testen, war mir nur schwer möglich.
Er sollte aber auch nicht allzu dringend sein, da er ja fast nie auftritt.

Freundliche Grüße,
Justus Kempfer

**Comment by hydranox** [comment]
Kein Fehler, " die Zeigerpositionen der beiden Listen auf dem jeweils letzten Listelement, also |l1| und |l2|, die bekannte Abbruchbedingung." Falsch!
https://www.fachschaft.informatik.tu-darmstadt.de/forum//viewtopic.php?f=561&t=32284

**Comment by JustusKempfer** [comment]
Achso, dann ist das ja auch in anderen Fällen relevant.

Dann sollte man das aber vielleicht in der Aufgabenstellung erwähnen, dass dieser Optimierungsschritt angewendet wird.

Wenn ich mir nämlich den Algorithmus im Wiki anschaue (was ich getan habe), weiß man davon nichts.
Außerdem sind dann die Abbruchbedingung und Invariante anders.

**Comment by hydranox** [comment]
"Wenn ich mir nämlich den Algorithmus im Wiki anschaue (was ich getan habe), weiß man davon nichts.
Außerdem sind dann die Abbruchbedingung und Invariante anders."

Meeeeeh. Inkonsistenz zwischen Video und Wiki -> geht direkt an KW

**Comment by karweihe** [comment]
Am 26. Mai 2015 um 21:22 schrieb Thomas Lüdecke <notifications@github.com>:

> Meeeeeh. Inkonsistenz zwischen Video und Wiki -> geht direkt an KW
>

Habe den Wikieintrag geändert - immer noch inkonsistent?

-- 

Prof. Karsten Weihe
Hochschulstr. 10, 64289 Darmstadt, Germany
Phone: +49-6151-16-20870
Fax: +49-6151-16-20873
www.algo.informatik.tu-darmstadt.de

**Comment by hydranox** [comment]
Abstract View -> Break condition: Wohl nicht eher ein OR an dieser stelle?

**Comment by karweihe** [comment]
Yup, erledigt.

2015-05-26 21:33 GMT+02:00 Thomas Lüdecke <notifications@github.com>:

> Abstract View -> Break condition: Wohl nicht eher ein OR an dieser stelle?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hydranox/foo-pub/issues/172#issuecomment-105642972>.
>



-- 

Prof. Karsten Weihe
Hochschulstr. 10, 64289 Darmstadt, Germany
Phone: +49-6151-16-20870
Fax: +49-6151-16-20873
www.algo.informatik.tu-darmstadt.de

**Comment by hydranox** [comment]
@JustusKempfer Bitte schließen, wenn zufrieden.
Danke für die Anteilnahme und Sorry für diese Ungereimtheit :)

**Comment by JustusKempfer** [comment]
Kein Problem.

Abstract View -> Invariant macht aber so immer noch wenig Sinn, darauf hatte ich mich ja bei den foo-Tests immer verlassen, dass eben die Pointer in der Summe die Iteration ergeben.

**Comment by karweihe** [comment]
Jetzt?

Diese Zusatzfloskel wollte ich sowieso in den Invarianten diverser Algos
zur Klarstellung noch einfügen.

Am 26. Mai 2015 um 21:38 schrieb JustusKempfer <notifications@github.com>:

> Kein Problem.
>
> Abstract View -> Invariant macht aber so immer noch wenig Sinn, darauf
> hatte ich mich ja bei den foo-Tests immer verlassen, dass eben die Pointer
> in der Summe die Iteration ergeben.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hydranox/foo-pub/issues/172#issuecomment-105643836>.
>



-- 

Prof. Karsten Weihe
Hochschulstr. 10, 64289 Darmstadt, Germany
Phone: +49-6151-16-20870
Fax: +49-6151-16-20873
www.algo.informatik.tu-darmstadt.de

**Comment by JustusKempfer** [comment]
Oh, Verzeihung, ich meinte die Variante.
Aber ja, auch die gilt ja nur, solange die Terminierung noch nciht erreicht ist.
Danke für die Klärung.

**Comment by karweihe** [comment]
Ok, habe da die Klärung auch eingefügt, danke!

Am 26. Mai 2015 um 21:44 schrieb JustusKempfer <notifications@github.com>:

> Oh, Verzeihung, ich meinte die Variante.
> Aber ja, auch die gilt ja nur, solange die Terminierung noch nciht
> erreicht ist.
> Danke für die Klärung.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hydranox/foo-pub/issues/172#issuecomment-105644911>.
>



-- 

Prof. Karsten Weihe
Hochschulstr. 10, 64289 Darmstadt, Germany
Phone: +49-6151-16-20870
Fax: +49-6151-16-20873
www.algo.informatik.tu-darmstadt.de
