### ISSUE TITLE
foo Testat - Fehler gefunden

### ISSUE THREAD

**Issue by TristanGah** [hydranox/foo-pub#175]
Hallo, ich bin der Meinung einen Fehler gefunden zu haben. Folgende Aufgabe wurde mir heute in meinem Testat gestellt und die rot markierte Box soll angeblich 10 sein statt 11. Liege ich falsch oder ist dies ein Fehler seitens des Programmms?
![foo](https://cloud.githubusercontent.com/assets/12159787/7840218/9464d564-0496-11e5-8b85-1979abaa06d9.PNG)

**Comment by hydranox** [comment]
#129 Bitte vorher suchen.
