### ISSUE TITLE
ERROR 500 Internal Server Error Undefined offset: 22

### ISSUE THREAD

**Issue by yduman** [hydranox/foo-pub#198]
Ich bekomme diese Meldung bei der Merge Aufgabe. Egal, ob ich korrekte oder inkorrekte Werte eingebe. Nach der Meldung, muss ich die Aufgabe erneut machen und nach jeder Abgabe, wieder die selbe Meldung.

Grüße

**Comment by hydranox** [comment]
Seed bitte

**Comment by yduman** [comment]
Wie soll das gehen ? Ich kann die Aufgabe nicht abgeben, wegen dem Fehler und somit taucht sie nicht in der Übersichtsseite auf unter "Zuletzt erledigte Aufgaben".

**Comment by yduman** [comment]
ah ich glaube es ist:

9b04d152845ec0a378394003c96da594

**Comment by alexanderj1988** [comment]
ja das ist in der tat ein fehler...der index der abgefragt wird sollte nicht erscheinen....warum die random funktion trotz obere schranke nun doch mist baut verstehe ich nicht -.-

**Comment by yduman** [comment]
Gibt es da eine Möglichkeit das zu fixen ? Weil ich kann im Moment Merge-Aufgaben nur beim Account von einem Kommilitonen üben...

**Comment by hydranox** [comment]
Bitte prüfen

**Comment by alexanderj1988** [comment]
Ja, thomas muss deine session clearen. ich habe keinen zugriff auf den hauptserver
mfg Alex 


     Thomas Lüdecke <notifications@github.com> schrieb am 21:03 Montag, 1.Juni 2015:
   

 Bitte prüfen—

**Comment by yduman** [comment]
Ok ist gefixt ! Vielen Dank !
