### ISSUE TITLE
Bug in Merge

### ISSUE THREAD

**Issue by JumeVI** [hydranox/foo-pub#199]
Bei Merge wird beim Abgeben der Lösung manchmal ein falsches Ergebnis vorrausgesetzt.

Als Beispiel habe ich einige Screenshots angehängt:

![1](https://cloud.githubusercontent.com/assets/11291748/7881002/04589310-05ff-11e5-92eb-e0e9ca5caa69.PNG)
![2](https://cloud.githubusercontent.com/assets/11291748/7881004/0478af10-05ff-11e5-96d2-6e9daea18b33.PNG)
![3](https://cloud.githubusercontent.com/assets/11291748/7881003/0478b302-05ff-11e5-81c4-7bb965925024.PNG)

**Comment by SteffenPegenau** [comment]
Ich denke, ich habe den selben Bug gesichtet:
https://foo.algo.informatik.tu-darmstadt.de/solution/7/a1ba7595d9f1fa2fa235ba97c977a78a

i1 + i2 != i

Mir ist das vorhin schon mal passiert. Ebenfalls bei einem Datensatz, bei dem man fast alle Zahlen verteilen musste.

**Comment by hydranox** [comment]
Vielen Dank! Der Bug wurde bereits gesichtet. Er basiert auf einen Grauzone in der Spezifikation und diese wird z.Zt. geklärt.

**Comment by alexanderj1988** [comment]
naja, der eintrag mit dem pointer ist schlicht falsch. break condition ist, wenn einer der pointer die länge der liste erreicht hat.
nach dem erreichen der break condition geschieht das anhängen. es muss noch näher beläuchtet werden, ob das anhängen nach der schleife (post processing) oder noch in der schleife vorm raussprung passieren soll (im letzten fall würden die letzten beiden iterationen zusammen fallen) im ersten fall müsste was momentan als letzte iteration betrachtet wird als post processing bnetittelt werden

mfg alex

**Comment by joshimoo** [comment]
Hat sich hier noch etwas geändert oder ist die Evaluierung weiterhin so wie auf dem Screenshot?
Also mit anhängen und voller Liste ohne Pointer zu verschieben. (I1 + I2 != I)

**Comment by alexanderj1988** [comment]
ich weiß immer noch nicht wir ihr drauf kommt das i1 + i2 = l ist? das nicht teil der invariante oO 


     Joshua Moody <notifications@github.com> schrieb am 0:24 Mittwoch, 3.Juni 2015:
   

 Hat sich hier noch etwas geändert oder ist die Evaluierung weiterhin so wie auf dem Screenshot?
Also mit anhängen und voller Liste ohne Pointer zu verschieben. (I1 + I2 != I)—

**Comment by joshimoo** [comment]
Also bei mir kommt es von dem Video bei minute 3:50, hab noch nicht ins Wiki geschaut :+1: 
https://openlearnware.tu-darmstadt.de/#!/resource/merge-sort-1944

**Comment by alexanderj1988** [comment]
ok, ich kläre das ab. 


     Joshua Moody <notifications@github.com> schrieb am 19:11 Mittwoch, 3.Juni 2015:
   

 Also bei mir kommt es von dem Video bei minute 3:50, hab noch nicht ins Wiki geschaut  
https://openlearnware.tu-darmstadt.de/#!/resource/merge-sort-1944—
