### ISSUE TITLE
Fehler in Aufgabentext zu Merge

### ISSUE THREAD

**Issue by Pheasn** [hydranox/foo-pub#207]
Im Aufgabentext steht: "Gegeben sie den Stand der Ergebnissliste sowie die Zeigerposition von l1 und l2 zum Zeitpunkt i=22 an."

"Gegeben" -> "Geben"
"sie" -> "Sie"
"Ergebnissliste" -> "Ergebnisliste"

**Comment by hydranox** [comment]
Ja... unser Alex.....
zum Glück sind Textänderungen nicht im Rhamen des Releaseprozesses auszuführen.
Kommt gleich.

**Comment by hydranox** [comment]
Update eingespielt. Review läuft.

**Comment by hydranox** [comment]
![capture](https://cloud.githubusercontent.com/assets/9027061/7903695/532cd4b0-07e4-11e5-9e83-fa4e63937d42.PNG)
Review beendet. Ticket wird geschlossen.
