### ISSUE TITLE
Anführungszeichen in kleiner Beschreibung der Algorithmen sind falsch herum

### ISSUE THREAD

**Issue by Pheasn** [hydranox/foo-pub#210]
Die Anführungszeichen im div „well“ sollten überall einmal vertauscht werden.

![screenshot 18](https://cloud.githubusercontent.com/assets/2513555/7948549/1aa96aac-0985-11e5-9b1e-322a6371534e.png)

**Comment by hydranox** [comment]
Danke! Done!
