### ISSUE TITLE
Hashtable Quadratic Probing: Doppelte Werte 

### ISSUE THREAD

**Issue by BlackWiddow** [hydranox/foo-pub#213]
Servus!
EIn Kommilitone hat einen Bug bei Hashtable Quadratic festgestellt.
Nämlich hat er einen Wert an eine Stelle hineingezogen und dann festgestellt, dass dieser da
nicht hingehört. Nach dem er es berichtigt hatte, und abgegeben hat, wurde der Wert sowohl an der Neuen, als auch an der alten Stelle angezeigt.

![bildschirmfoto vom 2015-06-09 090849](https://cloud.githubusercontent.com/assets/9130071/8052383/7508c72a-0e87-11e5-855b-9eaf26f03af9.png)
Wäre cool wenn Ihr es beheben könntet :)

**Comment by hydranox** [comment]
Okay, mein Fehler :/
Ist nun gefixt. Danke!
