### ISSUE TITLE
Pivot Partitioning - Falsche Iteration in Lösung

### ISSUE THREAD

**Issue by DaCrashstar** [hydranox/foo-pub#216]
Hallo,
ich habe heute mehrere Pivot Partitoning Aufgaben gelöst und bei einer trat folgender Fehler auf:
![foo_pp_1](https://cloud.githubusercontent.com/assets/11227356/8087840/8d9258e4-0f9d-11e5-945e-732b5277c2d3.JPG)
![foo_pp_2](https://cloud.githubusercontent.com/assets/11227356/8087841/8d92fad8-0f9d-11e5-8469-7927c8449b35.JPG)
![foo_pp_3](https://cloud.githubusercontent.com/assets/11227356/8087839/8d91433c-0f9d-11e5-87b5-a6f50c09f6c9.JPG)
In der Lösung, die für die Korrektur der Aufgabe vorlag, war der Algorhitmus bis zur zweiten Iteration gelaufen, laut Aufgabenstellung war aber nur die erste gefordert.

**Comment by hydranox** [comment]
"In der Lösung, die für die Korrektur der Aufgabe vorlag, war der Algorhitmus bis zur zweiten Iteration gelaufen, laut Aufgabenstellung war aber nur die erste gefordert."
Nein?

**Comment by DaCrashstar** [comment]
Ach, ok, habe meinen Fehler gefunden, kein Bug.
Vielen Dank trotzdem :)

Am 10.06.2015 um 18:51 schrieb Thomas Lüdecke:
