### ISSUE TITLE
B-Tree: Delete: Live Preview der Eingabe

### ISSUE THREAD

**Issue by hydranox** [hydranox/foo-pub#217]
Die Eingabe der Nodes ist etwas langwierig und sollte man sich in der mitte vertun, dann verliert man die Übersicht, was man dann in dem Punkt ändern muss, bzw noch nicht abgearbeitet hat.

Ein Live Preview würde dieses Problem lösung und ist somit nicht mehr "Nice to have", sondern MR.

**Comment by jojowi** [comment]
Das wäre auf jeden Fall hilfreich. Vielleicht auch noch eine Möglichkeit den gegebenen Baum in die Ergebnisliste zu übertragen. Das würde viel Tipparbeit ersparen und man könnte sich auf den eigentlichen Algorithmus konzentrieren.
