### ISSUE TITLE
B-Tree delete: Zoom-Button ohne Funktion

### ISSUE THREAD

**Issue by jojowi** [hydranox/foo-pub#218]
Der Titel sagt eigentlich alles....

**Comment by hydranox** [comment]
Liegt am Firefox.
Die Live Preview klappt in dem auch noch nicht. Das Update mit #217 und Firefox Kompatiblität kommt entweder heute Abend oder morgen mittag.

**Comment by hydranox** [comment]
Sollte nun passen :dancer:
