### ISSUE TITLE
B-Tree: delete : Fehler beim Abgeben

### ISSUE THREAD

**Issue by jojowi** [hydranox/foo-pub#222]
Beim Abgeben mit einer bestimmten Lösung hat die Aufgabe einen Fehler geworfen. Hash: b193a092f2d6f4063f7f230cc1de3317
Als ich danach dieselbe Aufgabe mit der Starteingabe abgegeben habe ging es problemlos.
Die Lösung, bei der der Fehler auftrat sah aber in der Vorschau nicht ungewöhnlich aus und müsste sogar der Musterlösung entsprochen haben.
Anbei ein Bild der Fehlermeldung
![fehler](https://cloud.githubusercontent.com/assets/9122706/8157270/a7f5caa4-1353-11e5-9ba1-c5c108066101.png)

Viel Spaß bei der Fehlersuche ;)

**Comment by alexanderj1988** [comment]
Na das wird spaßig. Sieht so aus, das der Rest Server nicht geantwortet hat... 

Hm... Viel Spaß stefen xd

Von meinem Sony Xperia™-Smartphone gesendet

---- Johannes Wirth schrieb ----

**Comment by jojowi** [comment]
Hatte das selber Problem noch öfter, unter anderem bei folgender Aufgabe:
d0587ce3ade51f7805146d3edd6f1f8a

**Comment by FHees** [comment]
Hatte dasselbe Problem und nach ein bisschen Ausprobieren, glaube ich die Ursache zu haben:
Es scheint an Lücken in Kanten zu liegen (z.B: Kanten (0,0,5), (0,2,14), (0,3,21))
Aber nur wenn durch die Lösung der Aufgabe ein merge gefordert wird (Dann muss die "Lücke" im übergeordneten Knoten sein)
Probiert mal aus ob ihr den Error auch so reproduzieren könnt.

**Comment by FHees** [comment]
Noch eine bebilderte Anleitung:
Aufgabenstellung:
![error_00](https://cloud.githubusercontent.com/assets/12294561/8192766/ff027862-145f-11e5-8da8-8aa8e7a9a422.PNG)

Vor dem entscheidenen Merge:
![error_01](https://cloud.githubusercontent.com/assets/12294561/8192808/495a1b90-1460-11e5-8fdd-4e197b4aa2be.PNG)

Danach (Man beachte die fehlende Kante zwischen 49 und 75 im Wurzelknoten):
![error_02](https://cloud.githubusercontent.com/assets/12294561/8192825/70e23404-1460-11e5-8567-c5e5d5bfe04a.PNG)

Nach kompletten Lösen der Aufgabe mit Eingaben:
![error_03](https://cloud.githubusercontent.com/assets/12294561/8192849/91ed60f6-1460-11e5-9af6-c8da955ea90b.PNG)

Resultierender Error:
![error_04](https://cloud.githubusercontent.com/assets/12294561/8192867/a2746c6c-1460-11e5-961f-512b92c2720d.PNG)

Viel Spaß beim Fixen ;)

**Comment by jojowi** [comment]
Hier auch nochmal der Fehler bei mir. Im Forum wurde die Vermutung geäußert, dass es es an einem srcPointer="4" liegen könnte. Allerdings ist dies bei mir nicht vorhanden.
Hash:beab105a740056efe867b95bcb90b82d
Ich hab mir auch den kompletten xml-String gespeichert, falls der interessant ist. Kann ihn leider hier nicht hochladen. Bei Interesse melden

**Comment by SuperN1ck** [comment]
Meiner Meinung nach ist der Merge von @FHees korrekt, aber wieso verschiebst du die Kanten nicht mit? Du hast doch selbst gesehen, dass die Kante mit (0,1,xx) fehlt. Also (0,2,14), (0,3,21) jeweils um 1 nach links verschieben sollte passen. 
Dann ist ist auch der Baum korrekt. Bei deinem 3. Screenshot ist die 61 und 69 nämlich rechts von der 71, was nicht stimmt. Aber ich denke, dass du auch selbst bemerkt.
Hatte den selben Fehler und durch korrektes Verschieben der Kanten hat sich dieser behoben.

**Comment by FHees** [comment]
@SuperN1ck: Klar, aber es geht nicht darum, ob die abgegebene Lösung richtig oder falsch ist, sondern ob der Server mit allen möglichen Eingaben umgehen kann - Was er offensichtlich noch nicht tut.

Schöner wäre wenn es nicht zum Fehler 500 kommt sondern er bei der Auswertung sagt: "Das stimmt nicht was du gemacht hast" oder (besser noch) sogar vor der Abgabe: "Dein Baum ist syntaktisch nicht korrekt"
