### ISSUE TITLE
Pivot Partitioning_ i3 initial starting point false- pivot not element of Sequence

### ISSUE THREAD

**Issue by vauItTec** [hydranox/foo-pub#224]
The System returned a false result due to setting up i3 too far while pivot not being an element of the Input-sequence. While m1 and m2 are initially on the same starting position i2 and i3 should share the same starting position as well.

Hope you can still fix this before the first attestation.

PICS:

![p1](https://cloud.githubusercontent.com/assets/12940543/8215078/f582c5a2-152d-11e5-8837-b649aee74080.png)
![p2](https://cloud.githubusercontent.com/assets/12940543/8215084/f9adb268-152d-11e5-8ba0-ff46b355a0b7.png)
![p3](https://cloud.githubusercontent.com/assets/12940543/8215087/fc5111d6-152d-11e5-9e8a-3ad4d8b9044c.png)

**Comment by alexanderj1988** [comment]
iteration 0 is the induction basis / initialitation (thats why iteration 0 never gets asked only 1 onward)

(yes naming could be optimized on that point, but we wont change ui in the middle of the collocium)

so iteration 0 is the induction basis := i3 is on m2 and THAN gets moved forward until it points to an element which is smaler or equal the pivot element.

see http://wiki.algo.informatik.tu-darmstadt.de/index.php/Pivot_partitioning_by_scanning

mfg Alex

**Comment by vauItTec** [comment]
Right, I got it. My bad. 
Now it works.... :)
