### ISSUE TITLE
B-Tree: delete Was ist falsch?

### ISSUE THREAD

**Issue by alexanderj1988** [hydranox/foo-pub#225]
>[Lithanel]
>><cite>Ich habe leider keinen Plan, was hier falsch sein soll, denn egal wie oft ich drüberschaue, ich sehe nur 2 identische B-Bäume.
41bf9a159a04b2c5aad9f42d03eac490

![unbenannt](https://cloud.githubusercontent.com/assets/4067526/8215840/1036d302-1533-11e5-843a-1ba5303625a9.PNG)
</cite>

**Comment by alexanderj1988** [comment]
> [inf0rmatik0r]
>> <cite>Hatte hier gerade das selbe Problem 408ac1e5b2b05b63e650bd356018b62c - bitte prüfen!</cite>

Und noch einer.

**Comment by alexanderj1988** [comment]
> [Nullman]
>> <cite> Hallo zusammen,

>>hatte jetzt schon das zweite Mal bei dem B-Tree das gleiche Problem:
Wenn ich eine (wahrscheinlich richtige) Antwort abgebe, bekomme ich folgende Meldung (siehe unten). Wenn ich dann zur Übersicht zurück gehe und versuche eine neue Aufgabe zu starten, bekomme ich die exakt gleiche Aufgabe (weil sie ja noch nicht "beendet" wurde). Wenn ich nun das Gleiche wieder eintippe, kommt wieder der gleiche Fehler. Nur, wenn ich eine falsche Eingabe abgebe, wird es mir als falsch angezeigt und ich kann eine neue Aufgabe bekommen.

>> Seed der zweiten Aufgabe müsste sein: 02e444242f2d5b2e10f061dc0c37bb5c

>>Aufgabe 1:
![aufgabe1](https://cloud.githubusercontent.com/assets/4067526/8229056/dfe903ce-15b3-11e5-8545-e0d72ff85eed.png)

>>Aufgabe 2:
![aufgabe2](https://cloud.githubusercontent.com/assets/4067526/8229065/f2e70d72-15b3-11e5-9750-746b6a50d032.png)

</cite>

And again.

**Comment by foooooo** [comment]
Ich habe einen Tag vor dem Testat das gleiche Problem wie @alexanderj1988: die Aufgabe B-Tree: delete konnte zwei Mal nicht mit richtigem Ergebnis beendet werden. Beim dritten Mal (Knoten/Kanten in anderer Reihenfolge). Seed ist `cedd2be24694f54953031be877799777`.

**Comment by sh314** [comment]
Das Problem ist mittlerweile behoben, die Korrektur wird zeitnah online gestellt.
