### ISSUE TITLE
B-Tree Traverse Übung nicht möglich

### ISSUE THREAD

**Issue by MalteHe** [hydranox/foo-pub#228]
Bei meinem foo Account besteht derzeit eine unvollständige Übung, welche sich allerdings nicht öffnen lässt. Beim Versuch die Übung fortzusetzen, wird lediglich auf die foo Startseite verlinkt. Auch der Start einer neuen B-Tree Traverse Übung führt zur Startseite.

Das Problem besteht an verschiedenen Rechnern, sowie verschiedenen Browsern und scheint Accountbezogen zu sein.

Mit freundlichen Grüßen
Vanessa Tran

**Comment by hydranox** [comment]
Sollte nun passen.

Falls Sie sich durch den Vorfall nicht dazu im Stande sehen, am morgigen Testat teilzunehmen, kann ich Ihnen einen Ausweichtermin für die nächste Woche geben.

Sorry für die Umstände
