### ISSUE TITLE
Aufgabe "Double Hashing": Drag&Drop Boxen sind kaum sichtbar auf hellen Bildschirmen

### ISSUE THREAD

**Issue by GranatenArnold** [hydranox/foo-pub#231]
Hallo,
die Boxen, in die man die K's per Drag&Drop reinziehen soll, finde ich teilweise nur sehr schwer erkennbar und wuerde mich an dieser Stelle ueber kraeftigere Farben freuen.

Die Boxen werden vor allem nach unten hin immer heller.

Siehe Screenshot:

![fooinvisibleboxes](https://cloud.githubusercontent.com/assets/7962341/8285377/3d563b38-1903-11e5-9225-de7a219356fc.jpg)

**Comment by hydranox** [comment]
"Die Boxen werden vor allem nach unten hin immer heller."
Möglich, dass die Hintergrundbeleuchtung deines Monitors nachgibt? ;)

habe es von "#eee" -> "#aaa" geändert. Ist eine Änderung, die auch während der Testate gemacht werden darf.

**Comment by GranatenArnold** [comment]
"Möglich, dass die Hintergrundbeleuchtung deines Monitors nachgibt? ;)"
Daran habe ich noch gar nicht gedacht, ich hoffe nicht..

Danke fuer die Aenderung, jetzt sind die Boxen gut sichtbar!
