### ISSUE TITLE
Bug in Historie

### ISSUE THREAD

**Issue by GoodDayWorld** [hydranox/foo-pub#234]
![1970](https://cloud.githubusercontent.com/assets/13049685/8354873/aa2c1026-1b4b-11e5-9214-12db76de4e62.png)

Ich kann leider nicht sagen wie das zustande kam, aber ist ein kĺeiner Bug und ich wollte ihn nur mitteilen.

**Comment by hydranox** [comment]
Das passiert, wenn wir ein Aufgabenupdate einspielen, welches nicht mit einer vorher generierten Aufgabe eines Benutzers kompatibel ist. Wir setzen dann alle offenen Aufgaben als "bestanden" und lassen ein INT(0) Datum stehen.
