### ISSUE TITLE
B-Tree: remove - Typo in Textbaustein-Variable der Lösung

### ISSUE THREAD

**Issue by GrollTroll** [hydranox/foo-pub#237]
In der Lösung steht folgender Text:
"Der Knoten zu dem hinabgestiegen werden soll hat minimale Anzahl von Schlüsseln (d.h. M - 1 Schlüssel). Es könnte dort also nicht ohne weiteres gelöscht werden. Der rechte Geschwisterknoten hat mehr als M - 1 Schlüssel, es wird daher eine <b>Shift_Key_to_Sibling-Operaion</b> mit dem rechten Geschwisterknoten durchgeführt."

Da fehlt wahrscheinlich nur ein "t" in Shift_Key_to_Sibling-Opera<b>t</b>ion, damit der Text korrekt angezeigt werden kann.

Beispiel Seed: 6d94980a43c77975678b10419befff4e > Lösung > 2. Schritt + 4. Schritt

**Comment by hydranox** [comment]
Danke!
Fixed.
