### ISSUE TITLE
Dijkstra falsch generierter Graph & Internal Server Error

### ISSUE THREAD

**Issue by Brotus** [hydranox/foo-pub#239]
Gestern wurde dieser Dijkstra-Graph generiert:
![dijkstra1](https://cloud.githubusercontent.com/assets/7878667/8478089/7004a974-20cf-11e5-89af-1d2b6c9e33df.png)
Das ist offensichtlich kein zusammenhängender/zulässiger Graph. Wenn ich jedoch versuche eine beliebige Eingabe abzugeben, erhalte ich
![dijkstra2](https://cloud.githubusercontent.com/assets/7878667/8478145/bd63e568-20cf-11e5-8864-a830be7273c0.png)
Außerdem bleibt die Aufgabe als unbearbeitet eingetragen, sodass ich keine anderen Aufgaben generieren kann. Der seed aus der URL ist

5002d290ed597357ff82dd3275f0f324

**Comment by hydranox** [comment]
Dijkstra funktioniert auch auf nicht zusammenhängenden Graphen, ist auch insofern Absicht, dass das vorkommen kann, wurde auch getestet.

Nur warum er das hier an dieser Stelle irgendeinen Fehler verursacht, müssen wir nochmal überprüfen. Wird vermutlich nichts mit Knote h zu tun haben.

Ich habe den Versuche bei dir rausgenommen. Sorry :-/
