### ISSUE TITLE
Dijkstra: Problem

### ISSUE THREAD

**Issue by FBlaubaer** [hydranox/foo-pub#244]
Einen wunderschönen guten Abend allerseits,
ich habe ein kleines Problem mit foo: ich habe am Freitag Vormittag einen neuen Versuch Dijkstra gestartet, allerdings bin ich nie zu der Bearbeitungsseite Vorgedrungen. Stattdessen beförderte mich derKlick auf "Neuen Versuch starten" auf die Übersichtsseite. Dort wird mir zwar ein laufender Versuch angezeigt, aber ich kann ihn nicht bearbeiten. Diese Lage hat sich bis Heute auch nicht grundlegend verändert, was ärgerlich ist, da ich am Montag morgen das entsprechende Testat habe und auch bestehen will.

Bellman-Ford konnte ich allerdings zwischendurch erfolgreich bearbeiten, also scheint das Problem nur mit Dijkstra zu bestehen.

Es wäre ausgesprochen schön, wenn sich jemand trotz des Wochenendes ein klitzekleines bisschen darum kümmern könnte.

**Comment by hydranox** [comment]
Gehts wieder? Hab einen Fix eingespielt, der dafür sorgt, dass das in Zukunft nicht mehr passiert.

**Comment by hydranox** [comment]
#251
