### ISSUE TITLE
Problem Djisktra

### ISSUE THREAD

**Issue by loewensge** [hydranox/foo-pub#245]
Ich kann meine Aufgabe bei Djikstra nicht beenden, da ich immer eine Error-Meldung erhalte : 

ERROR 500 Internal Server Error
Undefined index: (a, 41.317591116653, 94.24038765061)

In meinem Graph ist aber auch der Startknoten nicht in den Graphen eingebunden!

Kann jetzt auch keine andere Aufgabe mehr von Djisktra lösen, da dann immer automatisch die alte geöffnete geladen wird.

**Comment by hydranox** [comment]
Seed...?

**Comment by hydranox** [comment]
Wir haben den Fehler gefunden: #251
