### ISSUE TITLE
Fehler bei Auswertung (verify)

### ISSUE THREAD

**Issue by PrimeGhostDE** [hydranox/foo-pub#247]
![image](https://cloud.githubusercontent.com/assets/13138756/8513529/07e861d4-2370-11e5-8713-88fd1c9053f1.png)

Beim Abschicken meines Formulares gab es dieses Problem...
Reproduktion (dazu habe ich leider keine Ahnung wie das passieren konnte.)

Ich habe den Request / Response Network-Traffic per Chrome als HAR codiert speichern lassen,
dennoch kann ich diesen hier nicht hochladen.
Deshalb eine kurze Meldung mit entsprechender Email-Addresse, dann kann ich ihnen diese Daten auch zukommen lassen.
Gruß

Prime

**Comment by PrimeGhostDE** [comment]
könnte mit #245 zusammenhängen.

**Comment by hydranox** [comment]
Das ist eine Schutzmaßnahme, die im Normalfall nicht passiert.
Ein GET ist nämlich nicht auf den Verfiy State erlaubt. Nur POSTs (Absenden eines Formulars)
Sowas passiert z.B. wenn man während des States F5 (Aktualisieren) drückt oder man diese URL manuell aufruft.

Was mich an dieser Stelle allerdings irritiert ist der Anhang in deiner URL.
?ticket=blablabla ist nicht dort vorgesehen und kann dort auch nicht gehandelt werden o.O

**Comment by PrimeGhostDE** [comment]
ich habe lediglich die Übung über Abschicken abgeschlossen.
Aber ein F5 Aufruf habe ich nicht gemacht und die Parameter habe ich nicht geändert.

**Comment by hydranox** [comment]
Nochmal bezüglich der URL: Kann es sein, dass deine HRZ Authentifikation vom SSO genau in diesem Moment ausgelaufen ist? Das dauert immer ca 30 Min bzw. einen IP Wechsel.

**Comment by PrimeGhostDE** [comment]
Ich hoffe nicht... Kann aber sein... War zwischendrin noch essen...

**Comment by hydranox** [comment]
Okay, mir ist es heute auch passiert und es ist nun bestätigt.
#250
