### ISSUE TITLE
Fehler bei Prim 

### ISSUE THREAD

**Issue by WaterCooler8** [hydranox/foo-pub#260]
Bei dem Seed: e1c8d71fb48352a25b874b3be08a5899
Wird die Q: " g , j " als falsch gezeichnet, korrekte Lösung " g , j " ^^  
Außerdem sollte es, soweit ich verstanden hatte, ja egal sein, ob in Itteration  5 die Kante  " D-B " oder " A - B " genommen wird da beide gleichwertig sind, oder?

**Comment by hydranox** [comment]
Schau dir noch mal die Bedeutung von Q an ;-)

**Comment by WaterCooler8** [comment]
Die Bedeutung ist mir durchaus klar, ich habe ja in den meisten fällen auch kein Problem damit diese Aufgabe in Foo zu lösen, aber  wie man hier gut sieht 
![2](https://cloud.githubusercontent.com/assets/13314616/8649916/c01100aa-296e-11e5-8e8e-578f2394028a.JPG)    wenn selbst die Lösung sagt dass es eben G und J sind die in Q verbleiben, scheint meine Lösung ja eigentlich richtig zu sein oder nicht?  ich meine ich bin nicht gut in mathe aber G,J = G,J  sollte doch stimmen  oder über sehe ich grade etwas ? // außerdem ging es vor allem um den Punkt das in Itterarrtion 5 die Kante A - B  mit dem Wert 4  die gleiche Wertigkeit haben müsste wie die Kante D - B mit der Wert 4, also sollte es ja keine Unterschied welche der Beiden Kannten benutzt wird oder?

**Comment by alexanderj1988** [comment]
du hast g, j angegeben aber j, g ist richtig 


     WaterCooler8 <notifications@github.com> schrieb am 14:57 Montag, 13.Juli 2015:
   

 Die Bedeutung ist mir durchaus klar, ich habe ja in den meisten fällen auch kein Problem damit diese Aufgabe in Foo zu lösen, aber wie man hier gut sieht 
 wenn selbst die Lösung sagt dass es eben G und J sind die in Q verbleiben, scheint meine Lösung ja eigentlich richtig zu sein oder nicht? ich meine ich bin nicht gut in mathe aber G,J = G,J sollte doch stimmen oder über sehe ich grade etwas ? // außerdem ging es vor allem um den Punkt das in Itterarrtion 5 die Kante A - B mit dem Wert 4 die gleiche Wertigkeit haben müsste wie die Kante D - B mit der Wert 4, also sollte es ja keine Unterschied welche der Beiden Kannten benutzt wird oder? —

**Comment by WaterCooler8** [comment]
Ok, und wie sieht es mit den Kanten A-B anstatt D-B aus? 

-----Original Message-----

**Comment by alexanderj1988** [comment]
Du hast angegeben:
Q = (g,j)
Mu war:
Q = (j,g)

(g,j)  != (j,g) 


     WaterCooler8 <notifications@github.com> schrieb am 15:14 Montag, 13.Juli 2015:
   

 Ok, und wie sieht es mit den Kanten A-B anstatt D-B aus? 

-----Original Message-----

**Comment by alexanderj1988** [comment]
ups falsch gelesen.

Die Menge V wird ist chronologisch geordnet (wie auch in der mu immer zu sehen) und wird auch immer in der Reihenfolge durchgegangen. 

Du hast recht, das beide möglichkeiten eine richtige Lösung sind, aber dafür müsste man einen Lösungsbaum erstellender bei jedem iterationsschritt den algo mit allen permutationen von V an der stelle weiter berechnet (schlichtweg nein dazu).

Daher wird eine sortierung für die V Menge benutzt. Diese ist chronologisch geordnet. Das heißt nach wiki induction step wird in kombination mit der sortierung immer die letzte kante genommen die gefunden wird.

Hinweis dafür wurde in die Aufgabenstellung eingepflegt.


Danke für den Hinweis!
