### ISSUE TITLE
Fehler bei Djikstra

### ISSUE THREAD

**Issue by TiSan** [hydranox/foo-pub#261]
Auch hier liegt meiner Meinung nach ein Fehler bei der Bestimmung des kürzesten Pfads vor: 27ea5e6775ab5a1e9b8e7950add566df
Dort wird für h der Wert 9 angenommen, dieser kann jedoch nicht möglich sein. 10 ist der kleinstmögliche Wert, der die Spalte h in der Tabelle annehmen kann. ??

**Comment by alexanderj1988** [comment]
i -> c -> b -> d -> h = 9
mfg Alex 


     TiSan <notifications@github.com> schrieb am 20:14 Montag, 13.Juli 2015:
   

 Auch hier liegt meiner Meinung nach ein Fehler bei der Bestimmung des kürzesten Pfads vor: 27ea5e6775ab5a1e9b8e7950add566df
Dort wird für h der Wert 9 angenommen, dieser kann jedoch nicht möglich sein. 10 ist der kleinstmögliche Wert, der die Spalte h in der Tabelle annehmen kann. ??—
