### ISSUE TITLE
Kruskal: Mengen löschen nicht möglich

### ISSUE THREAD

**Issue by katrinBe** [hydranox/foo-pub#263]
Hallo!
Bei der Aufgabe zu Kruskal ist es nicht möglich, die Mengen zu löschen, der Button funktioniert nicht, es passiert bei drücken einfach gar nichts.
Was zur Folge hat, das bei am Ende überflüssigen (und dann eigentlich leeren) Mengen der Inhalt, der irgendwann mal drin stand, als "Eingabe" angenommen wird, was zu Fehlern führt.

**Comment by hydranox** [comment]
Ist gefixt :)
