### ISSUE TITLE
Kruskal: Verschieben von einer Menge in andere

### ISSUE THREAD

**Issue by alexanderj1988** [hydranox/foo-pub#264]
Verschieben von einer Menge in anderer entfernt nicht das Element aus der alten Menge und das Element wird somit verdoppelt.

**Comment by hydranox** [comment]
Nicht reproduzierbar meinerseits.

**Comment by alexanderj1988** [comment]
schauen wir uns morgen nochmal zusammen an, ich hab des auch

mfg alex

**Comment by hydranox** [comment]
Gefixt :)
