### ISSUE TITLE
Dijkstra

### ISSUE THREAD

**Issue by WaterCooler8** [hydranox/foo-pub#265]
Im Seed:  c96e2166d723fa5c68225995b2d227f4 
wird der kürzeste Pfad von E nach C in Iteration 4  mit 12 angegeben,  
und erst in Iteration 7 auf 11  reduziert. 
Der Pfad von E über G über B über F nach C  hat jedoch die länge 11 
und sollte schon deutlich vor Itteration 7 verfügbar sein ,
oder übershe ich garde etwas? ^^ 

![unbenannt](https://cloud.githubusercontent.com/assets/13314616/8681057/843a0ff2-2a65-11e5-9f60-cb63734d0d91.JPG)

**Comment by alexanderj1988** [comment]
Stichwort priority queue, Es wird immer ein Knoten betrachtet, nicht alle gleichzeitig

Das ist kein Bellman!

**Comment by alexanderj1988** [comment]
ich gebe dir aber recht, das die solution page bis zur klausur noch einmal überarbeitet werden sollte.

**Comment by WaterCooler8** [comment]
ah, stimmt danke für den Hinweis ^^

**Comment by alexanderj1988** [comment]
ok, dann schließe ich das ticket

mfg alex
