### ISSUE TITLE
Kruksal: Keine Mengen mehr erstellbar

### ISSUE THREAD

**Issue by FHees** [hydranox/foo-pub#267]
Wenn man die **oberste Menge löscht**, können keine weiteren Mengen mehr hinzugefügt werden.
Der Inhalt der Menge scheint keine Rolle zu spielen.

Was vieleicht auch damit zusammenhängt:
Bei einer "frischen" Aufgabe kann man die oberste (und dann ja auch einzige) Menge nicht löschen, das geht erst nachdem man eine weitere Menge erstellt hat.
Sobald man eine andere Menge erstellt hat kann man alle Mengen löschen (Reihenfolge egal), so dass keine mehr übrig bleibt.

**Comment by hydranox** [comment]
Ist gefixt.
