### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by PrimeGhostDE** [hydranox/foo-pub#271]
Ich habe eben mal wieder nach Foo gesehen, aber scheinbar lässt es mich nicht ran...
Liegt wahrscheinlich nicht an mir ;-)

Error:
Undefined offset: 0

**Comment by PrimeGhostDE** [comment]
PS: Liegt nur am Countdown Applet weil diese Seite lässt sich aufrufen:
https://foo.algo.informatik.tu-darmstadt.de/exerciselist/graph

**Comment by hydranox** [comment]
Jup.. der Case stand seit mehreren Wochen auf der TODO und ich kam leider noch nicht dazu.
Wir bei einem kommenden Refactoring der Frontpage obsolet.
Demnach Closed.
