### ISSUE TITLE
Sicherheit: Fehlermeldung bei falscher URL zu einer Solution

### ISSUE THREAD

**Issue by georg-jung** [hydranox/foo-pub#273]
Hey,

ich hab mich dafür interessiert, was es für einen Unterschied (z.B. von der Art der Darstellung) macht, wenn in der URL ´tsolution´ oder ´solution´ steht. Ich hab das dann kurz ausprobiert und dabei ist mir Folgendes aufgefallen:

Wenn die UUID nicht existiert, die in der URL steht, bekommt man die komplette Fehlermeldung zurückgegeben:
![2015-07-20_23-35-02](https://cloud.githubusercontent.com/assets/5229609/8788145/a83515d2-2f38-11e5-8ec4-b32625e062ce.png)

Ich habe das nicht weiter verfolgt, aber vielleicht könnte es jemand Böswilliges ausnutzen, dass foo die Eingabe aus der URL direkt in den Dateipfad integriert, an dem die Datei geladen werden soll (und dem User das auch mitteilt). Wahrscheinlich hat das für Euch verständlicherweise keine hohe Prio, aber ich dachte, ich schreibe es mal hier.

Viele Grüße
Georg

**Comment by hydranox** [comment]
An dieser Stelle liegt keine Sicherheitslücke vor.
Man kommt von außen nicht an die XML Files dran, in denen die Benutzereingaben und die Aufgaben stehen.
Zudem kann man auch nicht durch URL Scans die Aufgaben anderer User aufrufen (Außer man ist Kursleiter).
