### ISSUE TITLE
Foo-Aufgaben nicht startbar!

### ISSUE THREAD

**Issue by Godbull** [hydranox/foo-pub#276]
Kann momentan keine Foo-Aufgaben starten !
Es kommt bei allen Aufgaben die selbe Fehlermeldung seit heute .
![foo](https://cloud.githubusercontent.com/assets/11007712/9545650/2e9f30c8-4d8c-11e5-8266-73e148383c14.png)

LG Markus

**Comment by alexanderj1988** [comment]
Ist wohl das Backend abgeschmiert. Sollte so schnell wie möglich neu gestarted sein

mfg Alex
