### ISSUE TITLE
Internal Server Error 500 bei fast allen Aufgaben

### ISSUE THREAD

**Issue by Brotus** [hydranox/foo-pub#277]
Bei den Aufgaben Selectionsort, Insertionsort, Pivot Partitioning, Binary Search Tree: Traverse, B-Tree: insert, B-Tree: remove, Heap: insert, Heap: decrease key, Bellman-Ford, Floyd-Warshall, Prim und Kruskal erhalte ich folgenden Fehler:

![err](https://cloud.githubusercontent.com/assets/7878667/9547422/b1889dcc-4d9a-11e5-81d1-80489b4bc499.png)

(auch wenn sämtliche Plugins im Browser deaktiviert sind)

**Comment by alexanderj1988** [comment]
Das hat nichts mit euren Pllugins etc zu tun, das Backend ist abgeschmiert, kann aber Thomas nicht erreichen, damit er das Backend neu startet (was eigentlich bisher auch immer automatisch gegangen ist :/)
