### ISSUE TITLE
Heap: decrease key - falsche Lösung

### ISSUE THREAD

**Issue by m-ober** [hydranox/foo-pub#278]
Aufgabe: Reduzieren Sie den Schlüssel mit ID = 3 auf den Wert Key = 8. Geben Sie den Heap und das Array Positions nach der Iteration i := 2 an.

In der Musterlösung wird der Key von ID = 4 geändert. Kurz: Die Musterlösung bearbeitet nicht ID, sondern ID+1.

**Comment by user9209** [comment]
Kann ich auch bestätigen:

Foo-ID: 7fd0dd89af96a9e3127889b213866910

Reduzieren Sie den Schlüssel mit ID = 5 auf den Wert Key = 4. Geben Sie den Heap und das Array Positions nach der Iteration i := 3 an. 

Lösung ändert ID = 6 statt der 5

Bitte korrigieren.

**Comment by robtothein** [comment]
Weiterer Fehler der auch zu einer falschen Lösung führt: 4b59d3c6136a1b8cdd58e52df726845f
Man soll den Heap und das Array Positions nach der Iteration i := 2 angeben, aber die vorgeschlagene Lösung und Korrektur ist nach der Iteration i := 1. 

Hier ist auch der Fehler den die Benutzer über mir meinen.Man soll den Schlüssel mit ID = 0 reduzieren, aber bearbeitet wird ID = 1. (Für ID = 0 gibt es keinen Tabelleneintrag)

**Comment by FabianSchuessler** [comment]
Off by one Error existiert noch
https://foo.algo.informatik.tu-darmstadt.de/solution/10/6e9c5a6734985c4b7274c67a8f0cd965
