### ISSUE TITLE
Selection Sort - Eingabe in Ergebnisliste nicht möglich

### ISSUE THREAD

**Issue by MalteHe** [hydranox/foo-pub#283]
Ich kann lediglich das "m" bei Selection-Sort angeben, die Ergebnisliste ist grau hinterlegt und lässt keine Eingaben zu. Getestet habe ich es mit Google Chrome (unter OSX und Win 10) und Safari (OSX). Unter Safari lässt sich der Button zum fortfahren anklicken und mir wird angezeigt, dass ich die Aufgabe fehlerhaft gelöst hätte.

![ss](https://cloud.githubusercontent.com/assets/12952192/9838132/7691ae76-5a55-11e5-9a7f-0e897b4f0905.PNG)

**Comment by MalteHe** [comment]
Das gleiche Problem habe ich auch bei "Insertion Sort"!?

**Comment by witness357** [comment]
Hast du das gleiche Problem bei "Insertion Sort" ? (sprich ist das Fragezeichen fehl am Platz in "Das gleiche Problem habe ich auch bei "Insertion Sort"!?")

**Comment by hydranox** [comment]
Ggf. NoScript oder irgendwelche Extensions, die die JQuery UI aushebeln?

Schau mal in der Konsole unter Ctrl - Shift - L und realoade die Page. Sind da irgendwelche merkwürdigen Fehler von Javascript/Jquery?

**Comment by robtothein** [comment]
Ihr müsst bei Selection Sort die Felder aus der Ausgangssequenz in die Ergebnisliste <b>ziehen</b>. Nichts eingeben, außer m.

**Comment by hydranox** [comment]
War DAS der Fehler? Vllt. eine Info bezüglich Drag n Drop einfügen..

**Comment by MalteHe** [comment]
Ahh ups, mein Fehler. Danke, das mit Drag n Drop war für mich nicht so ersichtlich, das funktioniert.
