### ISSUE TITLE
B-Tree: insert appearently correct answer is marked incorrect

### ISSUE THREAD

**Issue by GeneralGeki** [hydranox/foo-pub#287]
Screenshot from:
https://foo.algo.informatik.tu-darmstadt.de/solution/21/42e297b32cfdc68ef25252d1adb7b48a
Last visited: Day of upload.

![insert-issue](https://cloud.githubusercontent.com/assets/10200056/9934244/5a104b6a-5d50-11e5-9bbe-7939290c12d9.png)

**Comment by sh314** [comment]
Leider sind Pointerverschiebungen in der Eingabe weder im Preview noch in der späteren EIngabedarstellung zu erkennen, im XML-Log allerdings schon. Der Baum ist nicht ganz korrekt obwohl er so aussieht.
