### ISSUE TITLE
Aufgabe Merge: Schönheitsfehler

### ISSUE THREAD

**Issue by hydranox** [hydranox/foo-pub#29]
![screen shot 2015-03-17 at 21 42 53](https://cloud.githubusercontent.com/assets/9027061/7024872/14f63da4-dd40-11e4-8f19-5c09d10065a0.png)
![screen shot 2015-03-17 at 21 43 04](https://cloud.githubusercontent.com/assets/9027061/7024874/17148212-dd40-11e4-9b46-72f344c4e91d.png)
(In Safari 8.0.5, OSX 10.10.3, Adblock Plus installiert)

**Comment by alexanderj1988** [comment]
lässt sich nicht behandeln, da dies vom framework falsch interpretiert wird.
