### ISSUE TITLE
Simple String Matching Formulierung

### ISSUE THREAD

**Issue by hydranox** [hydranox/foo-pub#31]
Musste zuerst überlegen, was mit "aktuellem Zeiger des Matchers" gemeint sein könnte. Dass das Beispiel der Kandidatenmenge eine Kombination enthält, die nie auftreten kann, war dabei auch nicht hilfreich.
Bezeichnung der Spalten verwirrend, habe die Kandidaten bei "C" eingetragen, aber sie wurden bei "R" erwartet?!

**Comment by alexanderj1988** [comment]
behoben.
