### ISSUE TITLE
String matching based on finite automaton

### ISSUE THREAD

**Issue by hydranox** [hydranox/foo-pub#32]
Es ist nicht angegeben, in welchem Format R eingegeben werden soll (oder was da überhaupt stehen soll, auch wenn man es vermuten kann)
    Im Stringmatcher kam der Buchstabe p vor, dieser war aber in der Tabelle nicht vorgesehen (siehe Screenshot)
    Richtige Eingaben wurden teilweise rot gekennzeichnet (siehe z.B. Iteration 9 auf dem ersten Screenshotpaar, oder die gesamte Spalte auf dem zweiten Screenshotpaar)
    Braucht man wirklich separate Felder für Current und Next State, wenn in Current State sowieso immer der Next State der vorherigen Zeile steht?
    starke Schwankungen zwischen den Aufgaben, hatte zuerst einen String mit 5 unterschiedlichen Buchstaben, 12 Buchstaben und 23 Iterationen, dann einen mit 8 unterschiedlichen Buchstaben, 16 Buchstaben und 31 Iterationen.
    Schön, dass man, statt 0 in die Felder einzugeben, die Felder auch leer lassen kann, ein Hinweis darauf wäre aber noch gut
    Schwierigkeit war okay
    Dauer ca. 25-30 Minuten, ist mMn auch mit viel Training in 15 Minuten nicht vernünftig machbar, dafür sind der Stringmatcher und der zu durchsuchende String zu lang

**Comment by alexanderj1988** [comment]
behoben
