### ISSUE TITLE
Zeilennummern Bug PHP

### ISSUE THREAD

**Issue by alexanderj1988** [hydranox/foo-pub#87]
Bei einem Fehler gibt der PHP-interpreter nicht mehr die Zeilennummern/Datei an in der der Fehler entstanden ist. Dies verlängert das Debuggen ungemein. Bitte so schnell wie möglich fixen, besonders, da dieser Bug schon länger bekannt ist.

**Comment by hydranox** [comment]
![buggestbug](https://cloud.githubusercontent.com/assets/9027061/7076467/ed74147e-df09-11e4-9f14-3627e37c98e0.PNG)
Kann somit, auch von Steffen bestätigt, geschlossen werden.
