### ISSUE TITLE
Logoauswahl

### ISSUE THREAD

**Issue by alexanderj1988** [hydranox/foo-pub#89]
In der Logoauswahl ist kein hinweis vorhanden, welches Logo nun animiert ist und welches nicht.
Des weiteren ist der Titel "Animiertes Logo" irreführend. Besser wäre "Logoauswahl" und mit untertitel auf eine Animation hindeuten.

**Comment by hydranox** [comment]
![captions](https://cloud.githubusercontent.com/assets/9027061/7070839/d4f73610-dee1-11e4-9a1d-6cc1d1650854.PNG)
