### ISSUE TITLE
Simple String Matching: Rechtschreibfehler

### ISSUE THREAD

**Issue by hydranox** [hydranox/foo-pub#90]
Ist ja fast schon peinlich....
![ernsthaft](https://cloud.githubusercontent.com/assets/9027061/7079564/23ffa802-df26-11e4-8069-239aeb1115da.PNG)

**Comment by alexanderj1988** [comment]
des weiteren wird getrennt geschrieben

**Comment by alexanderj1988** [comment]
Indices wird auch im deutschen so geschrieben
rest hab ich ausgebessert

**Comment by hydranox** [comment]
Satzanfang: Entweder "Des Weiteren" oder "Desweiteren" Großschreibung ist das Problem hier.

Indizes
Indizes Von Duden empfohlene Schreibung: Indizes | Alternative Schreibung: Indices Worttrennung: In|di|zes, In|di|ces Plural von Index. OK

**Comment by alexanderj1988** [comment]
gefixt
